const res = {
    convolution:{
        filterSize:0,
        stride:0,
        numFilters:0,
        padding:0,
        filters:[[]]
    },
    network:{
        size:[],
        learningLate:Number,
        info:[
            {
                neural:{
                    index:Number,
                    bias:Number,
                    next_links:[
                        {
                            weight:Number,
                            error:Number,
                            active:Number
                        }
                    ],
                    prev_links:[
                        {
                            weight:Number,
                            error:Number,
                            active:Number
                        }
                    ],
                    sum:Number,
                    output:Number,
                    error:Number,
                    cost:Number
                }
            }
        ]
    }
}